// <auto-generated />
using IBM.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SESCAP.Ecommerce.Database;

namespace SESCAP.Ecommerce.Migrations
{
    [DbContext(typeof(Db2Context))]
    [Migration("20220701182228_CriaTabelaCadastroLoginSescAp")]
    partial class CriaTabelaCadastroLoginSescAp
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Db2:ValueGenerationStrategy", Db2ValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("SESCAP.Ecommerce.Models.CadastroLoginSescAP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MATRICULA")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("CADASTRO_LOGIN_SESCAP");
                });
#pragma warning restore 612, 618
        }
    }
}
