// <auto-generated />
using System;
using IBM.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SESCAP.Ecommerce.Database;

namespace SESCAP.Ecommerce.Migrations
{
    [DbContext(typeof(Db2Context))]
    [Migration("20230413130600_Cria_Tabela_PagamentoOnline")]
    partial class Cria_Tabela_PagamentoOnline
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Db2:ValueGenerationStrategy", Db2ValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.25");

            modelBuilder.Entity("SESCAP.Ecommerce.Models.CadastroLoginSescAP", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("CPF")
                        .IsRequired()
                        .HasColumnType("varchar(14)")
                        .HasMaxLength(14);

                    b.Property<string>("EMAIL")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.Property<string>("MATRICULA")
                        .IsRequired()
                        .HasColumnType("varchar(13)")
                        .HasMaxLength(13);

                    b.Property<string>("SENHA")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasMaxLength(255);

                    b.HasKey("ID");

                    b.ToTable("CADASTRO_LOGIN_SESCAP");
                });

            modelBuilder.Entity("SESCAP.Ecommerce.Models.PagamentoOnline", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CDUOP")
                        .HasColumnType("int");

                    b.Property<DateTime>("DataPgto")
                        .HasColumnType("timestamp(6)");

                    b.Property<string>("FormaPgto")
                        .HasColumnType("varchar(20)")
                        .HasMaxLength(20);

                    b.Property<string>("OrderId")
                        .HasColumnType("varchar(60)")
                        .HasMaxLength(60);

                    b.Property<int?>("SQMATRIC")
                        .HasColumnType("int");

                    b.Property<string>("Status")
                        .HasColumnType("varchar(50)")
                        .HasMaxLength(50);

                    b.Property<decimal>("Total")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Transacao")
                        .HasColumnType("varchar(3000)")
                        .HasMaxLength(3000);

                    b.HasKey("Id");

                    b.ToTable("PAGAMENTO_ONLINE");
                });
#pragma warning restore 612, 618
        }
    }
}
