//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SESCAP.Ecommerce.Libraries.Lang {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Mensagem {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Mensagem() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("SESCAP.Ecommerce.Libraries.Lang.Mensagem", typeof(Mensagem).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string MSG_E01 {
            get {
                return ResourceManager.GetString("MSG_E01", resourceCulture);
            }
        }
        
        internal static string MSG_E02 {
            get {
                return ResourceManager.GetString("MSG_E02", resourceCulture);
            }
        }
        
        internal static string MSG_E03 {
            get {
                return ResourceManager.GetString("MSG_E03", resourceCulture);
            }
        }
        
        internal static string MSG_E04 {
            get {
                return ResourceManager.GetString("MSG_E04", resourceCulture);
            }
        }
        
        internal static string MSG_E05 {
            get {
                return ResourceManager.GetString("MSG_E05", resourceCulture);
            }
        }
        
        internal static string MSG_E06 {
            get {
                return ResourceManager.GetString("MSG_E06", resourceCulture);
            }
        }
    }
}
